### ISSUE TITLE
Nested Query

### ISSUE THREAD

**Issue by Chutchev** [volans-/gjson-py#3]
Hi!
I have JSON like this
```json
{
    "next": null,
    "previous": null,
    "results": [
        {
            "id": "uuid_4",
            "user": {
                "id": "user_uuid_4",
                "email": "student_email",
                "first_name": "student_name",
                "last_name": "student_last_name"
            },
            "program": {
                "id": "program_uuid_4",
                "name": "program_name"
            },
            "is_completed": false,
            "access": {
                "id": "access_uuid_4",
                "status": "open",
                "lock_reason": null
            },
            "teacher_id": "teacher_uuid_4",
            "teacher": {
                "id": "teacher_uuid_4",
                "email": "teacher_email",
                "first_name": "teacher_name",
                "last_name": "teacher_last_name"
            }
        }
    ]
}
```

I want find results.id with using filter by program.name. I use this expression: `results.#(program.name=="program_name").id`, but it's not working. I get error: **"gjson.exceptions.GJSONParseError: Query for first element does not match anything."** What I am doing wrong?

**Comment by volans-** [comment]
@Chutchev Thanks for reporting this. Your query is _correct_ in the sense that works fine with upstream GJSON but there is a bug that doesn't let you query for the nested level.
I'll look into into fixing this, but in the meanwhile I think you could use a workaround using multipaths:

```
results.#.{id,program.name}.#(name=="program_name")#.id|0
```

This is using the return all query syntax `#(...)#` and then taking the first element. If you expect more items to match just remove the `|0` part and use the returning list of IDs.
I'll have also a look at a secondary problem that I see that is that the simpler query for first item fails, so don't simplify the above with because it would not work:
```
results.#.{id,program.name}.#(name=="program_name").id
```

**Comment by Chutchev** [comment]
Thank you!
